---
title: "Projects"
description: |
  A list of my current and former projects, both at Fred Hutch and through external collaborations, such as Hackathons. 
author:
  - name: Jenny Smith
    url: https://www.linkedin.com/in/jenny-leopoldina-smith/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Projects 

* 2021 Bringing Genomics Data to the Clinic Hackathon
  * [Project link](https://osf.io/afc7n/)
  * [Github repository](https://github.com/collaborativebioinformatics/snpReportR)

* 2018 Consensus Machine Learning for Gene Target Selection in Pediatric AML Risk: NCBI Hackathon
  * [Manuscript](https://doi.org/10.1101/632166)
  * [Github repository](https://github.com/NCBI-Hackathons/ConsensusML)


# Selected Publications 

*	Huang, B., **Smith, J. L.**, Wang, J., Taghizadeh, K., … Meshinchi, S. CBFB-MYH11 Fusion Transcripts Distinguish Acute Myeloid Leukemias with Distinct Molecular Landscapes and Outcomes. Blood Advances 2021. [DOI: 10.1182/bloodadvances.2021004965](10.1182/bloodadvances.2021004965)

*	Chisholm, K., Heerema-McKenney, A., Choi, J., **Smith, J.L.** … Kahwash, B. Acute erythroid leukemia is enriched in NUP98 fusions: a report from the Children’s Oncology Group. Blood Advances 2020. [DOI: 10.1182/bloodadvances.2020002712](10.1182/bloodadvances.2020002712)

*	Noort, S., Wander, P., Alonzo, T. A., **Smith, J.L.**, … Meshinchi, S.  The clinical and biological characteristics of NUP98-KDM5A in pediatric acute myeloid leukemia. Haematologica 2020. [DOI: 10.3324/haematol.2019.236745](10.3324/haematol.2019.236745)

*	**Smith, J. L.**, Ries, R. E., Hylkema, T., Alonzo, T. A, … Meshinchi, S. Comprehensive Transcriptome Profiling of Cryptic CBFA2T3-GLIS2 Fusion-positive AML Defines Novel Therapeutic Options – A COG and TARGET Pediatric AML Study. Clinical Cancer Research 2019.  [DOI: 10.1158/1078-0432.CCR-19-1800](10.1158/1078-0432.CCR-19-1800)

*	**Smith, J.L.**, Maden S. K., Lee,  D., Buie, R.,  … Busby, B. Consensus Machine Learning for Gene Target Selection in Pediatric AML Risk. bioRxiv 2019. [DOI: 10.1101/632166](10.1158/1078-0432.CCR-19-1800)

*	Noort, S., Zimmermann, M., Reinhardt, D., Cuccuini, W., Pigazzi, M., **Smith, J.**, … Zwaan, C. M. Prognostic impact of t(16;21)(p11;q22) and t(16;21)(q24;q22) in pediatric AML: a retrospective study by the I-BFM Study Group. Blood 2018. [DOI: 10.1182/blood-2018-05-849059](10.1182/blood-2018-05-849059)

[Additional Publications](https://orcid.org/0000-0003-0402-2779)

# Presentations

*	**American Society for Hematology**, poster on ETS Family Transcription Factor Fusions in Childhood AML: Distinct Expression Networks and Clinical Implications (Virtual, 2021).

*	**American Society for Hematology**, poster on The Transcriptomic Landscape of NUP98-Rearranged Pediatric Acute Myeloid Leukemia (Virtual, 2020).

*	**Molecular Medicine Tri-conference**, panelist on AI in Genomics and Precision Medicine (San Francisco, CA, 2020).

*	**American Society for Hematology**, poster on Long Non-Coding RNAs (lncRNAs) Are Highly Associated with Disease Characteristics and Outcome in Pediatric Acute Myeloid Leukemia - a COG and Tpaml Study (Orlando, FL, 2019).

*	**Brotman Baty Pediatric Sequencing Symposium**, oral presentation on Long Non-coding RNAs Associate with Outcome in Pediatric Acute Myeloid Leukemia (Seattle, WA, 2019).

*	**American Society for Hematology**, oral presentation on Comprehensive Transcriptome Profiling of Cryptic CBFA2T3-GLIS2 Fusion-Positive AML Defines Novel Therapeutic Options — a COG and Target Pediatric AML Study (San Diego, CA, 2018). 

*	**American Society for Hematology**, oral presentation on The LSC17 Leukemic Stem Cell Signature Predicts Outcome in Pediatric Acute Myeloid Leukemia. Abstract Achievement Award Recipient (Atlanta, GA, 2017).




